<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>net.ectemplate</groupId>
	<artifactId>ectemplate</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>ectemplate</name>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.6</version>
		<relativePath/>
		<!-- lookup parent from repository -->
	</parent>

	<modules>
		<module>ectemplate-service-config-server</module>
		<module>ectemplate-servicio-eureka-server</module>
		<module>ectemplate-service-oauth</module>
		<module>ectemplate-servicio-personas</module>
		<module>ectemplate-servicio-productos</module>
		<!-- <module>ectemplate-service-zuul-server</module> -->
		<module>ectemplate-servicio-gateway</module>
	</modules>

	<packaging>pom</packaging>
	
  	<properties>
		<java.version>8</java.version>
		<spring-cloud.version>2020.0.6</spring-cloud.version>
   		<sonar.organization>rpuigmorganitation</sonar.organization>
    	<sonar.host.url>https://sonarcloud.io</sonar.host.url>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  	</properties>

</project>
